# Environment-specific configurations

staging:
  app:
    web:
      base_url: "https://staging.clearcaptions.com"
    api:
      base_url: "https://api-staging.clearcaptions.com"
  database:
    host: "staging-db.clearcaptions.com"
  credentials:
    admin_email: "admin-staging@clearcaptions.com"

production:
  app:
    web:
      base_url: "https://www.clearcaptions.com"
    api:
      base_url: "https://api.clearcaptions.com"
  database:
    host: "prod-db.clearcaptions.com"
  credentials:
    admin_email: "admin@clearcaptions.com"

local:
  app:
    web:
      base_url: "http://localhost:3000"
    api:
      base_url: "http://localhost:8000"
  database:
    host: "localhost"
  credentials:
    admin_email: "admin@local.clearcaptions.com"
